version: '3'
services:
  hdl-buspro-mqtt:
    build: .
    network_mode: host
    volumes:
      - /home/oleksandr/homeassistant-hdl-mqtt/homeassistant/config/configuration.yaml:/configuration.yaml:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
